### ISSUE TITLE
Add SR parameters.

### ISSUE THREAD

**Issue by soseigocho** [soseigocho/LuminanceLimiterSG#12]
# Add SR parameters.
## Overview
Add attack, sustain, release time and knee parameters to control limiting transitions.

## Purpose
To automate the luminance limiting transitions on sequences so that they are natural.

## Background
People are uncomfortable with abrupt transitions.
But manually setting all parameters is a waste of time.

## Task
- [x] #13 Convert this project from scripts into a binary plugin.
- [x] ~~Implement attack time and knee.~~
- [x] ~~#17 There's no reason to convert this code from script to binary plugin.~~
- [x] Implement sustain time.
- [x] Implement release time.

**Comment by soseigocho** [comment]
#17 
The attack time and the knee are essentially undefinable on limiter.
We should not convert this project from script to binary plugin.
