### ISSUE TITLE
Convert this project from scripts to a binary plugin.

### ISSUE THREAD

**Issue by soseigocho** [soseigocho/LuminanceLimiterSG#13]
# Convert this project from scripts to a binary plugin.
## Overview
Convert from the current Lua script implementation into a C++ binary plugin.

## Purpose
#12 
To prepare for new features and performance optimizations.

# Background
#12
Attack time sequences require frames to look ahead for limiting.
However, AviUtl .anm scripts cannot read ahead frames, unlike filter plugins.

## Tasks
- [x] Select and set up a test framework.
- [x] Include the SDK by git submodule.
- [x] Verify the build flow.
- [x] Port the implementations.

**Comment by soseigocho** [comment]
#17 
We should not convert this project from script to binary plugin.

**Comment by soseigocho** [comment]
In AviUtl, obj.getpixeldata only returns RGBA 24bit data, so if we want to use YC48, we have to use obj.getpixel with "yc" or use the binary plugin form.
And most importantly, if we use RGBA 24bit data, we lose the advantage of being able to use pixel data that is out of range.
Then in the first case, we get unrealistic execution speed.
For these reasons, in the end we should convert this project from script to binary plugins again.
