### ISSUE TITLE
Add various interpolation methods.

### ISSUE THREAD

**Issue by soseigocho** [soseigocho/LuminanceLimiterSG#22]
# Add various interpolation methods.
## Overview
Implement curve interpolation methods.

## Purpose
I want characteristics functions with smooth variation.

## Background
Linear interpolation involves abrupt changes.
We tend to be uncomfortable with them.

## Task
- [x] Rewrite the linear interpolation method as a compatible function..
- [x] Implement Lagrange interpolation.
- [x] Implement Spline interpolation.
- [x] Commonize calls to characteristic functions.
