### ISSUE TITLE
Support for simultaneous use of this filter across multiple layers.

### ISSUE THREAD

**Issue by soseigocho** [soseigocho/LuminanceLimiterSG#43]
# Support for simultaneous use of this filter across multiple layers.

## Overview
Make this filter available multiple times on the same frame.

## Purpose
Allow this filter to be applied multiple times to the same frame to make it useful.

## Background
Because of some reasons, it may be better to limit shallowly by times and times rather than limiting deeply at once time that .

## Task
- [x] Encapsulate internal state into a class.
- [x] Enable switching of internal state for each filter object.
- [x] Manage so that no zombie instances remain.
