### ISSUE TITLE
Add compression function.

### ISSUE THREAD

**Issue by soseigocho** [soseigocho/LuminanceLimiterSG#52]
# Add compression function.
## Overview
Add compression functionality to extend the range of applications.

## Purpose
The limiter function alone is too abrupt to apply, and I want to apply it more gradually and smoothly.

## Background
Fundamentally, a limiter is a special kind of compressor, designed only for limited situations.

## Task
- [x] Implement a switch interface.
- [x] Refactor code in func_proc for to unify the interfaces.
- [ ] Implement the core compression functions.

**Comment by soseigocho** [comment]
I decided that I'll not implement compressor and amplifier.
