### ISSUE TITLE
Add some dithering methods.

### ISSUE THREAD

**Issue by soseigocho** [soseigocho/LuminanceLimiterSG#58]
# Add some dithering methods.
## Overview
Add Bayer matrix ordered dithering, an error diffusion dithering, and if I could, I would implement blue noise.

## Purpose
To remove the artifacts after image processing.

## Background
This plugin calculates the luminance regularized from 0.0 to 1.0.
Due to the specification, the edge of the luminance looks bad.

## Task
- [ ] Add Bayer matrix ordered dithering.
- [ ] Add error diffusion dithering.
- [ ] (Extra) Add blue noise.
